Feature/Add Rspec Tests
andromeda2510/rails-movie-rental-app pull request #2
Opened 2021-04-22 23:41 UTC by andromeda2510

add to gemfile and configure rspec and simplecov

2021-04-26 22:12 UTC, andromeda2510 commented
![image](https://user-images.githubusercontent.com/66088396/116157439-98a0da00-a6b2-11eb-8fb0-d25660ce6edd.png)

2021-04-29 03:29 UTC, DeadKennedyx requested changes
add the coverage folder to git ignore

2021-04-29 03:29 UTC, DeadKennedyx commented on .vscode/settings.json
> +    "editor.tabSize": 2
add this file to the git ignore

2021-04-29 18:20 UTC, andromeda2510 commented on .vscode/settings.json
> +    "editor.tabSize": 2
solved

2021-04-30 04:48 UTC, merged